name: CI Pipeline
on: [push, pull_request]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # ENVIRONMENT SETUP
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    # DEPENDENCY CACHING
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        
    # BUILD STAGE
    - name: Build the project
      run: mvn clean install
      # QUALITY GATE: Fails on compilation errors

    # TEST STAGE
    - name: Run tests
      run: mvn test
      # QUALITY GATE: Fails on test failures

    # LINTING STAGE
    - name: Checkstyle Lint
      run: mvn checkstyle:check
      # QUALITY GATE: Fails on style violations